name: Terraform CI/CD

concurrency:
  group: terraform-staging
  cancel-in-progress: true

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  TF_VERSION: 1.10.5
  AWS_REGION: ap-south-1
  LAMBDA_ARTIFACT_BUCKET: serverless-api-artifacts-mb

jobs:
  node-tests:
    name: Node Lint + Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npx eslint . && echo "ESLint passed successfully"

      - name: Run Unit Tests
        run: npm test

  security-scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: node-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          trivy --version

      - name: Scan Node dependencies
        run: trivy fs app --severity HIGH,CRITICAL --exit-code 1

      - name: Scan Terraform code
        run: trivy config terraform --severity HIGH,CRITICAL --exit-code 1

  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest
    needs: security-scan

    defaults:
      run:
        working-directory: terraform/environments/staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock-timeout=5m

  apply-staging:
    name: Deploy Staging
    needs: terraform-checks
    runs-on: ubuntu-latest
    environment: staging

    if: github.event_name == 'push'

    defaults:
      run:
        working-directory: terraform/environments/staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Build Lambda artifact
        run: |
          cd ../../../app
          npm ci --omit=dev
          zip -r ../lambda.zip .

      - name: Generate Lambda hash
        run: |
          cd ../../../
          echo "LAMBDA_HASH=$(openssl dgst -sha256 -binary lambda.zip | openssl base64)" >> $GITHUB_ENV

      - name: Upload Lambda artifact to S3
        run: |
          aws s3 cp ../../../lambda.zip \
            s3://${{ env.LAMBDA_ARTIFACT_BUCKET }}/lambda-${{ github.sha }}.zip

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -lock-timeout=5m \
            -var="lambda_artifact_key=lambda-${{ github.sha }}.zip" \
            -var="lambda_source_hash=${{ env.LAMBDA_HASH }}"

  apply-production:
    name: Deploy Production
    needs: apply-staging
    runs-on: ubuntu-latest
    environment: production

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: terraform/environments/production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Build Lambda artifact
        run: |
          cd ../../../app
          npm ci --omit=dev
          zip -r ../lambda.zip .

      - name: Generate Lambda hash
        run: |
          cd ../../../
          echo "LAMBDA_HASH=$(openssl dgst -sha256 -binary lambda.zip | openssl base64)" >> $GITHUB_ENV

      - name: Upload Lambda artifact to S3
        run: |
          aws s3 cp ../../../lambda.zip \
            s3://${{ env.LAMBDA_ARTIFACT_BUCKET }}/lambda-${{ github.sha }}.zip

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -lock-timeout=5m \
            -var="lambda_artifact_key=lambda-${{ github.sha }}.zip" \
            -var="lambda_source_hash=${{ env.LAMBDA_HASH }}"