name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to rollback"
        required: true
        type: choice
        options:
          - staging
          - production

      lambda_artifact_key:
        description: "Lambda artifact key in S3"
        required: true

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.10.5
  AWS_REGION: ap-south-1
  LAMBDA_ARTIFACT_BUCKET: serverless-api-artifacts-mb
  AWS_ROLE_ARN: arn:aws:iam::135808925550:role/github-actions-oidc-role

jobs:
  rollback:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download rollback artifact
        run: |
          aws s3 cp \
            s3://${{ env.LAMBDA_ARTIFACT_BUCKET }}/${{ github.event.inputs.lambda_artifact_key }} \
            /tmp/lambda.zip

      - name: Generate Lambda source hash
        run: |
          echo "LAMBDA_HASH=$(openssl dgst -sha256 -binary /tmp/lambda.zip | openssl base64)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Rollback Deployment
        run: |
          terraform apply -auto-approve -lock-timeout=5m -input=false \
            -var="lambda_artifact_key=${{ github.event.inputs.lambda_artifact_key }}" \
            -var="lambda_source_hash=${{ env.LAMBDA_HASH }}"